### ISSUE TITLE
Project scope and milestones

### ISSUE THREAD

**Issue by IDavGal** [Ekumen-OS/andino_webots#11]
Project milestones:
- [x] Set up the andino_webots package
    - [x] Launch a simple world in Webots using a ROS2 launchfile
    - [x] Spawn Andino from a plain URDF description in Webots
    - [x] Identify all sensors are present in the webots simulation (Albeit uninitialized)
- [x] Create webots URDF for Andino
    - [x] Initialize all devices
    - [x] Read Sensor output from ROS2 topics
- [x] Control Andino using diff drive
- [x] Spawn Andino on runtime
- [x] Create a functional custom plugin example
- [x] Write comparative document for Andino sim in Webots vs Gazebo
